# @package _group_

nq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-train

nq_train_hn1:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-adv-hn-train

nq_train_hn:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data/retriever/hn-train/nq-train-hn.json

nq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-dev

trivia_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-train

trivia_train_hn:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data/retriever/hn-train/trivia-train-hn.json

trivia_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-dev

squad1_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-train

squad1_train_hn:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data/retriever/hn-train/squad-train-hn.json

squad1_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-dev

webq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-train
  
webq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-dev
  
curatedtrec_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-train
  
curatedtrec_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-dev
    
